global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets:
        - 'tempo-compactor:3200'
        - 'tempo-distributor:3200'
        - 'tempo-ingester-0:3200'
        - 'tempo-ingester-1:3200'
        - 'tempo-ingester-2:3200'
        - 'tempo-querier:3200'
        - 'tempo-query-frontend:3200'
        - 'tempo-metrics-generator:3200'
